// flags from https://github.com/lipis/flag-icon-css

module.exports = [
  ['UN', 'International', []],
  ['AF', ' (‫افغانستان‬‎)', []],
  ['AX', 'AfghanistanÅland Islands', []],
  ['AL', 'Albania (Shqipëri)', ['sq-AL']],
  ['DZ', 'Algeria (‫الجزائر‬‎)', ['ar-DZ']],
  ['AS', 'American Samoa (Amerika Sāmoa)', []],
  ['AD', 'Andorra', []],
  ['AO', 'Angola', []],
  ['AI', 'Anguilla', []],
  ['AG', 'Antigua and Barbuda', []],
  ['AR', 'Argentina', ['es-AR']],
  ['AM', 'Armenia (Հայաստան)', ['hy-AM']],
  ['AW', 'Aruba', []],
  ['AU', 'Australia', ['en-AU']],
  ['AT', 'Austria (Österreich)', ['de-AT']],
  ['AZ', 'Azerbaijan (Azərbaycan)', ['Cy-az-AZ', 'Lt-az-AZ']],
  ['BS', 'Bahamas', []],
  ['BH', 'Bahrain (‫البحرين‬‎)', ['ar-BH']],
  ['BD', 'Bangladesh (বাংলাদেশ)', []],
  ['BB', 'Barbados', []],
  ['BY', 'Belarus (Беларусь)', ['be-BY']],
  ['BE', 'Belgium (België)', ['nl-BE', 'fr-BE']],
  ['BZ', 'Belize', ['en-BZ']],
  ['BJ', 'Benin (Bénin)', []],
  ['BM', 'Bermuda', []],
  ['BT', 'Bhutan (འབྲུག)', []],
  ['BO', 'Bolivia', ['es-BO']],
  ['BA', 'Bosnia and Herzegovina', []],
  ['BW', 'Botswana', []],
  ['BR', 'Brazil (Brasil)', ['pt-BR']],
  ['IO', 'British Indian Ocean Territory', []],
  ['VG', 'British Virgin Islands', []],
  ['BN', 'Brunei (Negara Brunei Darussalam)', ['ms-BN']],
  ['BG', 'Bulgaria (България)', ['bg-BG']],
  ['BF', 'Burkina Faso', []],
  ['BI', 'Burundi (Uburundi)', []],
  ['KH', 'Cambodia (កម្ពុជា)', []],
  ['CM', 'Cameroon (Cameroun)', []],
  ['CA', 'Canada', ['en-CA', 'fr-CA']],
  ['CV', 'Cape Verde (Kabu Verdi)', []],
  ['BQ', 'Caribbean Netherlands', []],
  ['KY', 'Cayman Islands', []],
  ['CF', 'Central African Republic', []],
  ['TD', 'Chad (Tchad)', []],
  ['CL', 'Chile', ['es-CL']],
  ['CN', 'China (中国)', ['zh-CN', 'zh-CHS', 'zh-CHT']],
  ['CX', 'Christmas Island', []],
  ['CC', 'Cocos (Keeling) Islands', []],
  ['CO', 'Colombia', ['es-CO']],
  ['KM', 'Comoros (‫جزر القمر‬‎)', []],
  ['CD', 'Congo (DRC) (Kongo)', []],
  ['CG', 'Congo (Republic) (Congo-Brazzaville)', []],
  ['CK', 'Cook Islands', []],
  ['CR', 'Costa Rica', ['es-CR']],
  ['CI', 'Côte d’Ivoire', []],
  ['HR', 'Croatia (Hrvatska)', ['hr-HR']],
  ['CU', 'Cuba', []],
  ['CW', 'Curaçao', []],
  ['CY', 'Cyprus (Κύπρος)', []],
  ['CZ', 'Czech Republic (Česká republika)', ['cs-CZ']],
  ['DK', 'Denmark (Danmark)', ['da-DK']],
  ['DJ', 'Djibouti', []],
  ['DM', 'Dominica', []],
  ['DO', 'Dominican Republic', ['es-DO']],
  ['EC', 'Ecuador', ['es-EC']],
  ['EG', 'Egypt (‫مصر‬‎)', ['ar-EG']],
  ['SV', 'El Salvador', ['es-SV']],
  ['GQ', 'Equatorial Guinea (Guinea Ecuatorial)', []],
  ['ER', 'Eritrea', []],
  ['EE', 'Estonia (Eesti)', ['et-EE']],
  ['ET', 'Ethiopia', []],
  ['FK', 'Falkland Islands (Islas Malvinas)', []],
  ['FO', 'Faroe Islands (Føroyar)', ['fo-FO']],
  ['FJ', 'Fiji (Matanitu Tugalala o Viti)', []],
  ['FI', 'Finland (Suomi)', ['fi-FI', 'sv-FI']],
  ['FR', 'France (République française)', ['fr-FR']],
  ['GF', 'French Guiana (Guyane française)', []],
  ['PF', 'French Polynesia (Polynésie française)', []],
  ['GA', 'Gabon (République gabonaise)', []],
  ['GM', 'Gambia', []],
  ['GE', 'Georgia (საქართველო)', ['ka-GE']],
  ['DE', 'Germany (Deutschland)', ['de-DE']],
  ['GH', 'Ghana (Gaana)', []],
  ['GI', 'Gibraltar', []],
  ['GR', 'Greece (Ελλάδα)', ['el-GR']],
  ['GL', 'Greenland (Kalaallit Nunaat)', []],
  ['GD', 'Grenada', []],
  ['GP', 'Guadeloupe', []],
  ['GU', 'Guam (Guåhån)', []],
  ['GT', 'Guatemala', ['es-GT']],
  ['GG', 'Guernsey', []],
  ['GN', 'Guinea (Guinée)', []],
  ['GW', 'Guinea-Bissau (Guiné Bissau)', []],
  ['GY', 'Guyana', []],
  ['HT', "Haiti (République d'Haïti)", []],
  ['HN', 'Honduras', ['es-HN']],
  ['HK', 'Hong Kong (香港)', ['zh-HK']],
  ['HU', 'Hungary (Magyarország)', ['hu-HU']],
  ['IS', 'Iceland (Ísland)', ['is-IS']],
  [
    'IN',
    'India (भारत)',
    [
      'gu-IN',
      'hi-IN',
      'kn-IN',
      'kok-IN',
      'mr-IN',
      'pa-IN',
      'sa-IN',
      'ta-IN',
      'te-IN',
    ],
  ],
  ['ID', 'Indonesia', ['id-ID']],
  ['IR', 'Iran (‫ایران‬‎)', ['fa-IR']],
  ['IQ', 'Iraq (‫العراق‬‎)', ['ar-IQ']],
  ['IE', 'Ireland', ['en-IE']],
  ['IM', 'Isle of Man', []],
  ['IL', 'Israel (‫ישראל‬‎)', ['he-IL']],
  ['IT', 'Italy (Italia)', ['it-IT']],
  ['JM', 'Jamaica', ['en-JM']],
  ['JP', 'Japan (日本)', ['ja-JP']],
  ['JE', 'Jersey', []],
  ['JO', 'Jordan (‫الأردن‬‎)', ['ar-JO']],
  ['KZ', 'Kazakhstan (Казахстан)', ['kk-KZ', 'ky-KZ']],
  ['KE', 'Kenya', ['sw-KE']],
  ['KI', 'Kiribati', []],
  ['KW', 'Kuwait (‫الكويت‬‎)', ['ar-KW']],
  ['KG', 'Kyrgyzstan (Кыргызстан)', []],
  ['LA', 'Laos (ລາວ)', []],
  ['LV', 'Latvia (Latvija)', ['lv-LV']],
  ['LB', 'Lebanon (‫لبنان‬‎)', ['ar-LB']],
  ['LS', 'Lesotho', []],
  ['LR', 'Liberia', []],
  ['LY', 'Libya (‫ليبيا‬‎)', ['ar-LY']],
  ['LI', 'Liechtenstein', ['de-LI']],
  ['LT', 'Lithuania (Lietuva)', ['lt-LT']],
  ['LU', 'Luxembourg (Lëtzebuerg)', ['fr-LU', 'de-LU']],
  ['MO', 'Macau (澳門)', ['zh-MO']],
  ['MK', 'Macedonia (FYROM) (Македонија)', ['mk-MK']],
  ['MG', 'Madagascar (Madagasikara)', []],
  ['MW', 'Malawi (Malaŵi)', []],
  ['MY', 'Malaysia', ['ms-MY']],
  ['MV', 'Maldives', ['div-MV']],
  ['ML', 'Mali', []],
  ['MT', 'Malta', []],
  ['MH', 'Marshall Islands', []],
  ['MQ', 'Martinique', []],
  ['MR', 'Mauritania (‫موريتانيا‬‎)', []],
  ['MU', 'Mauritius (Moris)', []],
  ['YT', 'Mayotte', []],
  ['MX', 'Mexico (México)', ['es-MX']],
  ['FM', 'Micronesia', []],
  ['MD', 'Moldova (Republica Moldova)', []],
  ['MC', 'Monaco', ['fr-MC']],
  ['MN', 'Mongolia (Монгол)', ['mn-MN']],
  ['ME', 'Montenegro (Crna Gora)', []],
  ['MS', 'Montserrat', []],
  ['MA', 'Morocco (‫المغرب‬‎)', ['ar-MA']],
  ['MZ', 'Mozambique (Moçambique)', []],
  ['MM', 'Myanmar (Burma) (မြန်မာ)', []],
  ['NA', 'Namibia (Namibië)', []],
  ['NR', 'Nauru (Repubrikin Naoero)', []],
  ['NP', 'Nepal (नेपाल)', []],
  ['NL', 'Netherlands (Nederland)', ['nl-NL']],
  ['NC', 'New Caledonia (Nouvelle-Calédonie)', []],
  ['NZ', 'New Zealand', ['en-NZ']],
  ['NI', 'Nicaragua', ['es-NI']],
  ['NE', 'Niger (Nijar)', []],
  ['NG', 'Nigeria', []],
  ['NU', 'Niue (Niuē)', []],
  ['NF', 'Norfolk Island', []],
  ['KP', 'North Korea (조선 민주주의 인민 공화국)', []],
  ['MP', 'Northern Mariana Islands', []],
  ['NO', 'Norway (Norge)', ['nb-NO', 'nn-NO']],
  ['OM', 'Oman (‫عُمان‬‎)', ['ar-OM']],
  ['PK', 'Pakistan (‫پاکستان‬‎)', ['ur-PK']],
  ['PW', 'Palau (Beluu er a Belau)', []],
  ['PS', 'Palestine (‫فلسطين‬‎)', []],
  ['PA', 'Panama (Panamá)', ['es-PA']],
  ['PG', 'Papua New Guinea', []],
  ['PY', 'Paraguay (Tetã Paraguái)', ['es-PY']],
  ['PE', 'Peru (Perú)', ['es-PE']],
  ['PH', 'Philippines (Republika ng Pilipinas)', ['en-PH']],
  ['PL', 'Poland (Polska)', ['pl-PL']],
  ['PT', 'Portugal (República Portuguesa)', ['pt-PT']],
  ['PR', 'Puerto Rico', ['es-PR']],
  ['QA', 'Qatar (‫قطر‬‎)', ['ar-QA']],
  ['RE', 'Réunion (La Réunion)', []],
  ['RO', 'Romania (România)', ['ro-RO']],
  ['RU', 'Russia (Россия)', ['ru-RU', 'tt-RU']],
  ['RW', 'Rwanda', []],
  ['BL', 'Saint Barthélemy (Saint-Barthélemy)', []],
  ['SH', 'Saint Helena', []],
  ['KN', 'Saint Kitts and Nevis', []],
  ['LC', 'Saint Lucia', []],
  ['MF', 'Saint Martin (Saint-Martin)', []],
  ['PM', 'Saint Pierre and Miquelon', []],
  ['VC', 'Saint Vincent and the Grenadines', []],
  ['WS', 'Samoa (Sāmoa)', []],
  ['SM', 'San Marino', []],
  ['ST', 'São Tomé and Príncipe', []],
  ['SA', 'Saudi Arabia (‫المملكة العربية السعودية‬‎)', ['ar-SA']],
  ['SN', 'Senegal (Sénégal)', []],
  ['RS', 'Serbia (Србија)', ['Cy-sr-SP', 'Lt-sr-SP']],
  ['SC', 'Seychelles (Repiblik Sesel)', []],
  ['SL', 'Sierra Leone', []],
  ['SG', 'Singapore (Singapura) (新加坡共和国)', ['zh-SG']],
  ['SX', 'Sint Maarten', []],
  ['SK', 'Slovakia (Slovensko)', ['sk-SK']],
  ['SI', 'Slovenia (Slovenija)', ['sl-SI']],
  ['SB', 'Solomon Islands', []],
  ['SO', 'Somalia (Soomaaliya)', []],
  ['ZA', 'South Africa', ['af-ZA', 'en-ZA']],
  ['KR', 'South Korea (대한민국)', ['ko-KR']],
  ['SS', 'South Sudan (‫جنوب السودان‬‎)', []],
  ['ES', 'Spain (España)', ['eu-ES', 'ca-ES', 'gl-ES', 'es-ES']],
  ['LK', 'Sri Lanka (ශ්‍රී ලංකාව)', []],
  ['SD', 'Sudan (‫السودان‬‎)', []],
  ['SR', 'Suriname', []],
  ['SJ', 'Svalbard and Jan Mayen', []],
  ['SZ', 'Swaziland (Umbuso weSwatini)', []],
  ['SE', 'Sweden (Sverige)', ['sv-SE']],
  ['CH', 'Switzerland (Schweiz)', ['fr-CH', 'de-CH', 'it-CH']],
  ['SY', 'Syria (‫سوريا‬‎)', ['ar-SY', 'syr-SY']],
  ['TW', 'Taiwan (台灣)', ['zh-TW']],
  ['TJ', 'Tajikistan (Ҷумҳурии Тоҷикистон)', []],
  ['TZ', 'Tanzania', []],
  ['TH', 'Thailand (ไทย)', ['th-TH']],
  ['TL', 'Timor-Leste (Timór-Leste)', []],
  ['TG', 'Togo (République togolaise)', []],
  ['TK', 'Tokelau', []],
  ['TO', 'Tonga', []],
  ['TT', 'Trinidad and Tobago', ['en-TT']],
  ['TN', 'Tunisia (‫تونس‬‎)', ['ar-TN']],
  ['TR', 'Turkey (Türkiye)', ['tr-TR']],
  ['TM', 'Turkmenistan (Türkmenistan)', []],
  ['TC', 'Turks and Caicos Islands', []],
  ['TV', 'Tuvalu', []],
  ['VI', 'U.S. Virgin Islands', []],
  ['UG', 'Uganda', []],
  ['UA', 'Ukraine (Україна)', ['uk-UA']],
  ['AE', 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)', ['ar-AE']],
  ['GB', 'United Kingdom', ['en-GB']],
  ['US', 'United States', ['en-US']],
  ['UY', 'Uruguay', ['es-UY']],
  ['UZ', 'Uzbekistan (Oʻzbekiston)', ['Cy-uz-UZ', 'Lt-uz-UZ']],
  ['VU', 'Vanuatu', []],
  ['VA', 'Vatican City (Città del Vaticano)', []],
  ['VE', 'Venezuela', ['es-VE']],
  ['VN', 'Vietnam (Việt Nam)', ['vi-VN']],
  ['WF', 'Wallis and Futuna (Wallis-et-Futuna)', []],
  ['EH', 'Western Sahara (‫الصحراء الغربية‬‎)', []],
  ['YE', 'Yemen (‫اليمن‬‎)', ['ar-YE']],
  ['ZM', 'Zambia', []],
  ['ZW', 'Zimbabwe', ['en-ZW']],
];
