// flags from https://github.com/lipis/flag-icon-css

module.exports = [
  ['AF', 'Afghanistan', []],
  ['AX', 'Åland Islands', []],
  ['AL', 'Albania', ['sq-AL']],
  ['DZ', 'Algeria', ['ar-DZ']],
  ['AS', 'American Samoa', []],
  ['AD', 'Andorra', []],
  ['AO', 'Angola', []],
  ['AI', 'Anguilla', []],
  ['AG', 'Antigua and Barbuda', []],
  ['AR', 'Argentina', ['es-AR']],
  ['AM', 'Armenia', ['hy-AM']],
  ['AW', 'Aruba', []],
  ['AU', 'Australia', ['en-AU']],
  ['AT', 'Austria', ['de-AT']],
  ['AZ', 'Azerbaijan', ['Cy-az-AZ', 'Lt-az-AZ']],
  ['BS', 'Bahamas', []],
  ['BH', 'Bahrain', ['ar-BH']],
  ['BD', 'Bangladesh', []],
  ['BB', 'Barbados', []],
  ['BY', 'Belarus', ['be-BY']],
  ['BE', 'Belgium', ['nl-BE', 'fr-BE']],
  ['BZ', 'Belize', ['en-BZ']],
  ['BJ', 'Benin', []],
  ['BM', 'Bermuda', []],
  ['BT', 'Bhutan', []],
  ['BO', 'Bolivia', ['es-BO']],
  ['BA', 'Bosnia and Herzegovina', []],
  ['BW', 'Botswana', []],
  ['BR', 'Brazil', ['pt-BR']],
  ['IO', 'British Indian Ocean Territory', []],
  ['VG', 'British Virgin Islands', []],
  ['BN', 'Brunei', ['ms-BN']],
  ['BG', 'Bulgaria', ['bg-BG']],
  ['BF', 'Burkina Faso', []],
  ['BI', 'Burundi', []],
  ['KH', 'Cambodia', []],
  ['CM', 'Cameroon', []],
  ['CA', 'Canada', ['en-CA', 'fr-CA']],
  ['CV', 'Cape Verde', []],
  ['BQ', 'Caribbean Netherlands', []],
  ['KY', 'Cayman Islands', []],
  ['CF', 'Central African Republic', []],
  ['TD', 'Chad', []],
  ['CL', 'Chile', ['es-CL']],
  ['CN', 'China', ['zh-CN', 'zh-CHS', 'zh-CHT']],
  ['CX', 'Christmas Island', []],
  ['CC', 'Cocos (Keeling) Islands', []],
  ['CO', 'Colombia', ['es-CO']],
  ['KM', 'Comoros', []],
  ['CD', 'Congo (DRC)', []],
  ['CG', 'Congo (Republic)', []],
  ['CK', 'Cook Islands', []],
  ['CR', 'Costa Rica', ['es-CR']],
  ['CI', 'Ivory Coast', []],
  ['HR', 'Croatia', ['hr-HR']],
  ['CU', 'Cuba', []],
  ['CW', 'Curaçao', []],
  ['CY', 'Cyprus', []],
  ['CZ', 'Czech Republic', ['cs-CZ']],
  ['DK', 'Denmark', ['da-DK']],
  ['DJ', 'Djibouti', []],
  ['DM', 'Dominica', []],
  ['DO', 'Dominican Republic', ['es-DO']],
  ['EC', 'Ecuador', ['es-EC']],
  ['EG', 'Egypt', ['ar-EG']],
  ['SV', 'El Salvador', ['es-SV']],
  ['GQ', 'Equatorial Guinea', []],
  ['ER', 'Eritrea', []],
  ['EE', 'Estonia', ['et-EE']],
  ['ET', 'Ethiopia', []],
  ['FK', 'Falkland Islands', []],
  ['FO', 'Faroe Islands', ['fo-FO']],
  ['FJ', 'Fiji', []],
  ['FI', 'Finland', ['fi-FI', 'sv-FI']],
  ['FR', 'France', ['fr-FR']],
  ['GF', 'French Guiana', []],
  ['PF', 'French Polynesia', []],
  ['GA', 'Gabon', []],
  ['GM', 'Gambia', []],
  ['GE', 'Georgia', ['ka-GE']],
  ['DE', 'Germany', ['de-DE']],
  ['GH', 'Ghana', []],
  ['GI', 'Gibraltar', []],
  ['GR', 'Greece', ['el-GR']],
  ['GL', 'Greenland', []],
  ['GD', 'Grenada', []],
  ['GP', 'Guadeloupe', []],
  ['GU', 'Guam', []],
  ['GT', 'Guatemala', ['es-GT']],
  ['GG', 'Guernsey', []],
  ['GN', 'Guinea', []],
  ['GW', 'Guinea-Bissau', []],
  ['GY', 'Guyana', []],
  ['HT', 'Haiti', []],
  ['HN', 'Honduras', ['es-HN']],
  ['HK', 'Hong Kong', ['zh-HK']],
  ['HU', 'Hungary', ['hu-HU']],
  ['IS', 'Iceland', ['is-IS']],
  ['IN', 'India', ['gu-IN', 'hi-IN', 'kn-IN', 'kok-IN', 'mr-IN', 'pa-IN', 'sa-IN', 'ta-IN', 'te-IN']],
  ['ID', 'Indonesia', ['id-ID']],
  ['IR', 'Iran', ['fa-IR']],
  ['IQ', 'Iraq', ['ar-IQ']],
  ['IE', 'Ireland', ['en-IE']],
  ['IM', 'Isle of Man', []],
  ['IL', 'Israel', ['he-IL']],
  ['IT', 'Italy', ['it-IT']],
  ['JM', 'Jamaica', ['en-JM']],
  ['JP', 'Japan', ['ja-JP']],
  ['JE', 'Jersey', []],
  ['JO', 'Jordan', ['ar-JO']],
  ['KZ', 'Kazakhstan', ['kk-KZ', 'ky-KZ']],
  ['KE', 'Kenya', ['sw-KE']],
  ['KI', 'Kiribati', []],
  ['KW', 'Kuwait', ['ar-KW']],
  ['KG', 'Kyrgyzstan', []],
  ['LA', 'Laos', []],
  ['LV', 'Latvia', ['lv-LV']],
  ['LB', 'Lebanon', ['ar-LB']],
  ['LS', 'Lesotho', []],
  ['LR', 'Liberia', []],
  ['LY', 'Libya', ['ar-LY']],
  ['LI', 'Liechtenstein', ['de-LI']],
  ['LT', 'Lithuania', ['lt-LT']],
  ['LU', 'Luxembourg', ['fr-LU', 'de-LU']],
  ['MO', 'Macau', ['zh-MO']],
  ['MK', 'Macedonia', ['mk-MK']],
  ['MG', 'Madagascar', []],
  ['MW', 'Malawi', []],
  ['MY', 'Malaysia', ['ms-MY']],
  ['MV', 'Maldives', ['div-MV']],
  ['ML', 'Mali', []],
  ['MT', 'Malta', []],
  ['MH', 'Marshall Islands', []],
  ['MQ', 'Martinique', []],
  ['MR', 'Mauritania', []],
  ['MU', 'Mauritius', []],
  ['YT', 'Mayotte', []],
  ['MX', 'Mexico', ['es-MX']],
  ['FM', 'Micronesia', []],
  ['MD', 'Moldova', []],
  ['MC', 'Monaco', ['fr-MC']],
  ['MN', 'Mongolia', ['mn-MN']],
  ['ME', 'Montenegro (Crna Gora)', []],
  ['MS', 'Montserrat', []],
  ['MA', 'Morocco', ['ar-MA']],
  ['MZ', 'Mozambique', []],
  ['MM', 'Myanmar', []],
  ['NA', 'Namibia', []],
  ['NR', 'Nauru', []],
  ['NP', 'Nepal', []],
  ['NL', 'Netherlands', ['nl-NL']],
  ['NC', 'New Caledonia', []],
  ['NZ', 'New Zealand', ['en-NZ']],
  ['NI', 'Nicaragua', ['es-NI']],
  ['NE', 'Niger', []],
  ['NG', 'Nigeria', []],
  ['NU', 'Niue', []],
  ['NF', 'Norfolk Island', []],
  ['KP', 'North Korea', []],
  ['MP', 'Northern Mariana Islands', []],
  ['NO', 'Norway', ['nb-NO', 'nn-NO']],
  ['OM', 'Oman', ['ar-OM']],
  ['PK', 'Pakistan', ['ur-PK']],
  ['PW', 'Palau', []],
  ['PS', 'Palestine', []],
  ['PA', 'Panama', ['es-PA']],
  ['PG', 'Papua New Guinea', []],
  ['PY', 'Paraguay', ['es-PY']],
  ['PE', 'Peru', ['es-PE']],
  ['PH', 'Philippines', ['en-PH']],
  ['PL', 'Poland', ['pl-PL']],
  ['PT', 'Portugal', ['pt-PT']],
  ['PR', 'Puerto Rico', ['es-PR']],
  ['QA', 'Qatar', ['ar-QA']],
  ['RE', 'Réunion', []],
  ['RO', 'Romania', ['ro-RO']],
  ['RU', 'Russia', ['ru-RU', 'tt-RU']],
  ['RW', 'Rwanda', []],
  ['BL', 'Saint Barthélemy', []],
  ['SH', 'Saint Helena', []],
  ['KN', 'Saint Kitts and Nevis', []],
  ['LC', 'Saint Lucia', []],
  ['MF', 'Saint Martin', []],
  ['PM', 'Saint Pierre and Miquelon', []],
  ['VC', 'Saint Vincent and the Grenadines', []],
  ['WS', 'Samoa', []],
  ['SM', 'San Marino', []],
  ['ST', 'São Tomé and Príncipe', []],
  ['SA', 'Saudi Arabia', ['ar-SA']],
  ['SN', 'Senegal', []],
  ['RS', 'Serbia', ['Cy-sr-SP', 'Lt-sr-SP']],
  ['SC', 'Seychelles', []],
  ['SL', 'Sierra Leone', []],
  ['SG', 'Singapore', ['zh-SG']],
  ['SX', 'Sint Maarten', []],
  ['SK', 'Slovakia (Slovensko)', ['sk-SK']],
  ['SI', 'Slovenia (Slovenija)', ['sl-SI']],
  ['SB', 'Solomon Islands', []],
  ['SO', 'Somalia (Soomaaliya)', []],
  ['ZA', 'South Africa', ['af-ZA', 'en-ZA']],
  ['KR', 'South Korea', ['ko-KR']],
  ['SS', 'South Sudan', []],
  ['ES', 'Spain', ['eu-ES', 'ca-ES', 'gl-ES', 'es-ES']],
  ['LK', 'Sri Lanka', []],
  ['SD', 'Sudan', []],
  ['SR', 'Suriname', []],
  ['SJ', 'Svalbard and Jan Mayen', []],
  ['SZ', 'Swaziland', []],
  ['SE', 'Sweden', ['sv-SE']],
  ['CH', 'Switzerland', ['fr-CH', 'de-CH', 'it-CH']],
  ['SY', 'Syria', ['ar-SY', 'syr-SY']],
  ['TW', 'Taiwan', ['zh-TW']],
  ['TJ', 'Tajikistan', []],
  ['TZ', 'Tanzania', []],
  ['TH', 'Thailand', ['th-TH']],
  ['TL', 'Timor-Leste', []],
  ['TG', 'Togo', []],
  ['TK', 'Tokelau', []],
  ['TO', 'Tonga', []],
  ['TT', 'Trinidad and Tobago', ['en-TT']],
  ['TN', 'Tunisia', ['ar-TN']],
  ['TR', 'Turkey', ['tr-TR']],
  ['TM', 'Turkmenistan', []],
  ['TC', 'Turks and Caicos Islands', []],
  ['TV', 'Tuvalu', []],
  ['VI', 'U.S. Virgin Islands', []],
  ['UG', 'Uganda', []],
  ['UA', 'Ukraine', ['uk-UA']],
  ['AE', 'United Arab Emirates', ['ar-AE']],
  ['GB', 'United Kingdom', ['en-GB']],
  ['US', 'United States', ['en-US']],
  ['UY', 'Uruguay', ['es-UY']],
  ['UZ', 'Uzbekistan (Oʻzbekiston)', ['Cy-uz-UZ', 'Lt-uz-UZ']],
  ['VU', 'Vanuatu', []],
  ['VA', 'Vatican City', []],
  ['VE', 'Venezuela', ['es-VE']],
  ['VN', 'Vietnam', ['vi-VN']],
  ['WF', 'Wallis and Futuna', []],
  ['EH', 'Western Sahara', []],
  ['YE', 'Yemen', ['ar-YE']],
  ['ZM', 'Zambia', []],
  ['ZW', 'Zimbabwe', ['en-ZW']],
];
